version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lighthousedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lighthouse-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: plh-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - lighthouse-network
      
  minio:
    container_name: plh-minio-server
    image: minio/minio:latest
    ports:
      - "9008:9000"
      - "9009:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

  lighthouse-app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: lighthouse-app
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=lighthousedb;Username=admin;Password=admin
    depends_on:
      - postgres
    networks:
      - lighthouse-network

  vault:
    image: hashicorp/vault:latest
    container_name: plh-vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_ADDR: "http://localhost:8200"
      VAULT_DEV_LISTEN_ADDRESS: "vault:8200"
    privileged: true

  redis:
    image: redis:latest
    container_name: plh-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  minio_data:

networks:
  lighthouse-network:
    driver: bridge
